id: Tanium Threat Response - Request File Download
fromversion: ""
version: -1
contentitemfields:
  propagationLabels:
  - all
name: Tanium Threat Response - Request File Download
description: Requests a file download from Tanium.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d8c82418-fe27-4e68-880d-a871016a49af
    type: start
    task:
      id: d8c82418-fe27-4e68-880d-a871016a49af
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  "1":
    id: "1"
    taskid: 37898cab-ef34-4cb2-8120-77459d73ec0a
    type: regular
    task:
      id: 37898cab-ef34-4cb2-8120-77459d73ec0a
      version: -1
      name: tanium-tr-request-file-download
      description: Request a new file download.
      script: Tanium Threat Response|||tanium-tr-request-file-download
      type: regular
      iscommand: true
      brand: Tanium Threat Response
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      connection-id:
        simple: ${inputs.connection-id}
      path:
        simple: ${inputs.path}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  "2":
    id: "2"
    taskid: ba08ebe9-6939-4b3e-85ce-ea9cd96b8311
    type: playbook
    task:
      id: ba08ebe9-6939-4b3e-85ce-ea9cd96b8311
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: host,path
      AdditionalPollingCommandArgValues:
        simple: ${inputs.connection-id},${inputs.path}
      Ids:
        simple: ${Tanium.FileDownload.Downloaded}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: request-date
      PollingCommandName:
        simple: tanium-tr-get-download-file-request-status
      Timeout:
        simple: "10"
      dt:
        simple: Tanium.FileDownload(val.Status != 'Completed').ID
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  "3":
    id: "3"
    taskid: 544e1dad-1998-4feb-84e9-d6d564ffb89e
    type: title
    task:
      id: 544e1dad-1998-4feb-84e9-d6d564ffb89e
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  "5":
    id: "5"
    taskid: 3f60da64-6615-4342-881e-dfbaa0321ae8
    type: regular
    task:
      id: 3f60da64-6615-4342-881e-dfbaa0321ae8
      version: -1
      name: tanium-tr-delete-connection
      description: Delete a connection by connection name.
      script: Tanium Threat Response|||tanium-tr-delete-connection
      type: regular
      iscommand: true
      brand: Tanium Threat Response
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      connection-name:
        simple: ${inputs.connection-id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  "8":
    id: "8"
    taskid: 85c86dac-494b-45e0-8f8b-57c96feaac15
    type: condition
    task:
      id: 85c86dac-494b-45e0-8f8b-57c96feaac15
      version: -1
      name: Delete connection?
      type: condition
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.delete-connection
            iscontext: true
          right:
            value:
              simple: "true"
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  "9":
    id: "9"
    taskid: 766877f7-638d-45ca-8d30-274da1f6aeaf
    type: regular
    task:
      id: 766877f7-638d-45ca-8d30-274da1f6aeaf
      version: -1
      name: Get downloaded file
      description: Get the actual content of a downloaded file by file ID.
      script: Tanium Threat Response|||tanium-tr-get-downloaded-file
      type: regular
      iscommand: true
      brand: Tanium Threat Response
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      file-id:
        complex:
          root: Tanium
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: Tanium.FileDownload.Path
                iscontext: true
              right:
                value:
                  simple: inputs.path
                iscontext: true
          - - operator: isEqualString
              left:
                value:
                  simple: Tanium.FileDownload.Host
                iscontext: true
              right:
                value:
                  simple: inputs.connection-id
                iscontext: true
          accessor: FileDownload.ID
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  "10":
    id: "10"
    taskid: 64bba2d4-252f-4a4a-8ed2-287d40c94def
    type: condition
    task:
      id: 64bba2d4-252f-4a4a-8ed2-287d40c94def
      version: -1
      description: ""
      name: Should the file be downloaded?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.download-file
            iscontext: true
          right:
            value:
              simple: "true"
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  "11":
    id: "11"
    taskid: 19fbd9c1-0372-4363-88a1-3d2f1937475c
    type: playbook
    task:
      id: 19fbd9c1-0372-4363-88a1-3d2f1937475c
      version: -1
      name: Tanium Threat Response - Create Connection
      description: ""
      playbookName: Tanium Threat Response - Create Connection
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      connection-id:
        simple: ${inputs.connection-id}
      connection-timeout:
        simple: ${inputs.connection-timeout}
      destination-type:
        simple: ${inputs.destination-type}
      remote:
        simple: ${inputs.remote}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  "12":
    id: "12"
    taskid: a54d98f3-e4c0-4031-82d0-12408af79302
    type: regular
    task:
      id: a54d98f3-e4c0-4031-82d0-12408af79302
      version: -1
      name: tanium-tr-get-download-file-request-status
      description: Get the status of the download file request.
      script: Tanium Threat Response|||tanium-tr-get-download-file-request-status
      type: regular
      iscommand: true
      brand: Tanium Threat Response
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      host:
        simple: ${Tanium.FileDownload.Host}
      path:
        simple: ${Tanium.FileDownload.Path}
      request-date:
        simple: ${Tanium.FileDownload.Downloaded}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1610,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: connection-id
  value: {}
  required: true
  description: Connection ID.
- key: destination-type
  value: {}
  required: true
  description: 'Type of destination: ip_address or computer_name.'
- key: path
  value: {}
  required: true
  description: Path of file.
- key: download-file
  value:
    simple: "true"
  required: false
  description: If true, the file will be downloaded, otherwise, only a file download
    object will be created.
- key: delete-connection
  value:
    simple: "true"
  required: false
  description: If true, the connection will be deleted in the end of the playbook,
    otherwise, it will remain open.
- key: remote
  value: {}
  required: true
  description: True if remote connection.
- key: connection-timeout
  value: {}
  required: false
  description: Connection timeout, in milliseconds.
outputs:
- contextPath: File.ID
  description: File download entry ID.
  type: string
tests:
- Tanium Threat Response Test
